const mongoose = require("mongoose");
//Schema model for votes on jokes
const voteSchema = new mongoose.Schema({
  value: {
    type: Number,
    required: true,
    default: 0,
  },
  label: {
    type: String,
    required: true,
  },
});

//Schema model for Jokes, I didn't create ID because it is auto generated by MongoDB and its unique
const jokeSchema = new mongoose.Schema(
  {
    question: {
      type: String,
      required: true,
    },
    answer: {
      type: String,
      required: true,
    },
    votes: {
      type: [voteSchema], // Array of objects with value and label for voting
      required: true,
      default: [],
    },
    availableVotes: {
      type: [String], // Array of emoji strings for default vote labels, used for voting
      required: true,
      default: ["😂", "👍", "❤️"],
    },
    createdAt: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

const Joke = mongoose.model("Joke", jokeSchema);

module.exports = Joke;
